environment: {}
parameters: {}
packages:
  - name: pxy
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: redirect
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
